#!/usr/bin/env php
<?php

use RaceCli\Console\Application;
use Symfony\Component\Yaml\Yaml;

$autoload = require __DIR__ . '/vendor/autoload.php';

$container = require __DIR__ . '/bootstrap/bootstrap.php';

$app = new Application($container);

$app->run();